### PR TITLE
Run CI on macOS

### PR DESCRIPTION
**Pull request by bfirsh**
This is bound to catch some edge cases.

Signed-off-by: Ben Firshman <ben@firshman.co.uk>

### CODE REVIEW

**Comment by bfirsh** [comment]
Looks like they just get queued forever. :/

**Comment by bfirsh** [comment]
Looks like they started quicker that time, so maybe just intermittent

**Comment by bfirsh** [comment]
Worst case if this slows down builds, we can get a mac mini and run the builds ourselves. :)

**Comment by andreasjansson** [comment]
Great! 🍎

**Pull request merged**
